### ISSUE TITLE
Bing Maps not Displaying

### ISSUE THREAD

**Issue by drewteachout** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#18]
I am trying to create a bing map in an angular 4 web application, but the map will not display. My code previously displayed a map with this code.
```
setTimeout(()=> {
      var map = new Microsoft.Maps.Map('MyMap', {
        credentials: 'code',
        center: center,
        zoom: 11
      });
}, 200)
```

This issue has been occurring since 10/2.

I have an uncaught ReferenceError: DeprecatedClass is not defined, a ReferenceError: TravelAttractionEntity is not defined, and a ERROR ReferenceError: BirdseyeV2InfoExitControl is not defined.

I have also read that Bing Mpas AJAX Control v7 has reached end-of-life on 10/2 which is when I began experiencing this issue.

**Comment by rbrundritt** [comment]
Nothing changed in the API on 10/2. The issue is almost certainly the timeout, these won't work consistently as loading times will vary based on internet speeds and browsers. A time of 200ms might work for you in certain scenarios, but will fail in other browsers and on slower network speeds. Use the callback function parameter in the map script URL. It is specifically designed for this.

**Comment by drewteachout** [comment]
What is this callback function? Would I not be okay setting the timeout to something larger? For example, 2000ms?

**Comment by rbrundritt** [comment]
That may help sometimes, but still would still be a potential point of issue. If you are getting a Microsoft not defined error, that means the Microsoft.Maps namespace hasn't been loaded yet (i.e. map script).
