### ISSUE TITLE
@types/bingmaps

### ISSUE THREAD

**Issue by jefbarn** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#4]
Can you work with the typescript team to get this released on @types.
It's much easier to manage using npm that way without having to pull the definitions into a local project.
See
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by rbrundritt** [comment]
I'll look into it, but it doesn't look like those are managed by the TypeScript team at Microsoft. We have very specific rules we have to follow to make things open source, so not sure if this is an option or not. This is why we didn't make these appart of DefinatelyTyped.

**Comment by jefbarn** [comment]
Yeah, I've worked at Big Corporations before and know how much of a hassle it can be. 
Of course, the best answer would be to release the Bing Maps javascript api on NPM and include the typescript definitions along with the library, but oh how I dream.
Another option would be to add a typings.json to this repository then we can download with the typings tool using the "github:Microsoft/Bing-Maps-V8-TypeScript-Definitions" format.

**Comment by rbrundritt** [comment]
Ok, I'll put aside some time next week to try and get this setup on npm. I'll also reach out to the owners of @types project to see how best to link this there without moving this project.

**Comment by rolandoldengarm** [comment]
I would really like to see this! I've just switched to the new version of the Angular CLI (webpack) and it's no longer using typings.json, only "@types".

**Comment by rbrundritt** [comment]
I've had a talk with the author of that blog post. Going through this project he ended up recommending using DefinatelyTyped instead of @types for this project.

**Comment by rbrundritt** [comment]
These definitions are not available through npm. Simply type:
`npm install -g bingmaps`

**Comment by rolandoldengarm** [comment]
@rbrundritt I guess you mean now instead of not? :) Good stuff.

https://www.npmjs.com/package/bingmaps

**Comment by rbrundritt** [comment]
Correct. I meant "now" not "not". It was a long day yesterday :)

**Comment by cosmoKenney** [comment]
> @rbrundritt I guess you mean now instead of not? :) Good stuff.
> 
> https://www.npmjs.com/package/bingmaps

That package installs the bingmaps folder into node_modules, instead of @types/bingmaps. So the TypeScript compiler ignores the typings unless they are explicitly referenced.

**Comment by rbrundritt** [comment]
I left the Bing Maps team a year ago an no longer working on these. Doesn't look like any updates have been made to the NPM package by the Bing Maps team since I left. 

I'm on the Azure Maps team now. We also publish TypeScript definitions here: https://www.npmjs.com/package/azure-maps-control Soon we will also include the source code in the NPM package for easier embedding. Might be worth looking into if you are just starting your development.

**Comment by cosmoKenney** [comment]
Thanks, but we are entrenched in Bing. This is only coming up now as we are working on a conversion of all JS to TS and we are now using webpack to bundle. I had no idea about Azure maps. But the Typings definitely need to go into `@types` instead of being installed like a regular npm package. The TS compiler has special handling for `@types` which makes life really easy.

**Comment by cosmoKenney** [comment]
@rbrundritt , 
Thanks, but we are entrenched in Bing. This is only coming up now as we are working on a conversion of all JS to TS and we are now using webpack to bundle. I had no idea about Azure maps. But in either case the Typings definitely need to go into @types instead of being installed like a regular npm package. The TS compiler has special handling for @types which makes life really easy.
Maybe if you have any contacts on your old team you could give them a wink and a nudge? ;-)
